core/urls.py
# URLs (urls.py)

from django.urls import path
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views 
from .views import test_email
from .views import ForgotPasswordView, ResetPasswordView, VerifyOTPView

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('cookies/', views.cookies_view, name='cookies'),
    path('category/<int:category_id>/', views.category_items, name='category_items'),
    path('contact/', views.contact, name='contact'),
    path('student-portal/', views.student_portal, name='student_portal'),
    path('student-practical/', views.student_practical, name='student_practical'),
    path('about/', views.about, name='about'),
    path('gallery/', views.gallery, name='gallery'),
    path('ready-to-wear/', views.ready_to_wear, name='ready_to_wear'),
    path('ebook/', views.ebook, name='ebook'),
    path('training/', views.training, name='training'),
    path('custom-made/', views.custom_made, name='custom_made'),
    path('courses/', views.courses, name='courses'),
    path('market-place/', views.market_place, name='market_place'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile_view, name='profile_view'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.update_user, name='update_user'),
    path('account/delete/', views.delete_account, name='delete_account'),
    path('terms_and_conditions/', views.terms_and_conditions_view, name='terms_and_conditions'),
    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('verify_otp/', VerifyOTPView.as_view(), name='verify_otp'),
    path('reset_password/', ResetPasswordView.as_view(), name='reset_password'),
    path('faq/', views.faq_view, name='faq'),
    path('admin/', admin.site.urls),  # Default Django admin
    
]

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('upload-delete-videos/', views.upload_delete_videos, name='upload_delete_videos'),
    path('display-videos/', views.display_videos, name='display_videos'),
    path('delete/<int:video_id>/', views.delete_video, name='delete_video'),
    path('video/<int:video_id>/', views.view_video, name='view_video'),
    path('image-gallery/', views.image_gallery, name='image_gallery'),
    path('upload-delete-images/', views.upload_delete_images, name='upload_delete_images'),
    path('category/<int:category_id>/', views.category_view, name='category'),
    path('upload-assignment/', views.upload_assignment, name='upload_assignment'),
    path('assignments/', views.assignment_list, name='assignment_list'),
    path('upload-ebook/', views.upload_ebook, name='upload_ebook'),
    path('ebooks/', views.ebook_list, name='ebook_list'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('cart/', views.cart, name='cart'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('cart/add/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/update/<int:item_id>/', views.update_cart, name='update_cart'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
  path('gallery/', include('gallery.urls')),
    path('billing/', include('billing.urls')),
    path('', include('core.urls')),
    path('item/', include('item.urls', namespace='item')), 
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import secrets
from django.db import models
from django.conf import settings
from django.core.mail import send_mail
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.utils import timezone
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    postcode = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username




class otp_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    otp = models.IntegerField(null=True, blank=True)
    otp_created_at = models.DateTimeField(null=True, blank=True) 

    def is_otp_valid(self):
        if self.otp_created_at:
            now = timezone.now()
            time_difference = now - self.otp_created_at
            return time_difference <= timedelta(minutes=5)
        return False

    def __str__(self):
        return self.user.username
    
    


class Contact(models.Model):
    SERVICE_CHOICES = [
        ('Training', 'Training'),
        ('Ready to Wear Dress', 'Ready to Wear Dress'),
        ('Custom Made Dress', 'Custom Made Dress'),
        ('Others', 'Others'),
    ]

    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    service = models.CharField(max_length=50, choices=SERVICE_CHOICES)
    message = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.service}"

gallery/forms.py
from django import forms
from .models import Video, Image
from .models import Assignment
from .models import Ebook



class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['user', 'title', 'video_file', 'poster_image', 'description']

class VideoDeleteForm(forms.Form):
    video_ids = forms.CharField(widget=forms.HiddenInput())

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'image', 'description', 'category']

class DeleteImageForm(forms.Form):
    image_id = forms.CharField(widget=forms.HiddenInput())




class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['title', 'description', 'image']



class EbookForm(forms.ModelForm):
    class Meta:
        model = Ebook
        fields = ['title', 'description', 'upload_type', 'url', 'pdf']

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from item.models import Category, Item
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import SignupForm, LoginForm, UserUpdateForm, ProfileUpdateForm, PasswordResetRequestForm, SetPasswordForm, AccountDeletionForm
from .models import Profile
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth import update_session_auth_hash
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.utils.html import strip_tags
from conversation.models import ConversationMessage
from django.core.exceptions import ObjectDoesNotExist
import random
import logging
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.utils.encoding import force_str
import random
from django.core.exceptions import MultipleObjectsReturned
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.conf import settings
from datetime import datetime, timedelta
from django.utils import timezone
from .models import Profile, otp_Profile
from django.views import View 
from .forms import ContactForm








logger = logging.getLogger(__name__)

# View profile
@login_required
def profile_view(request):
    profile = request.user.profile
    return render(request, 'core/profile.html', {'profile': profile})



@login_required
def profile_view(request):
    try:
        profile = Profile.objects.get(user=request.user)
        otp_profile = otp_Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)  # Create profile if it doesn't exist
    except otp_Profile.DoesNotExist:
        otp_profile = otp_Profile.objects.create(user=request.user)  # Create otp_profile if it doesn't exist
    
    context = {
        'profile': profile,
        'otp_profile': otp_profile,
    }
    return render(request, 'core/profile.html', context)



# Update user profile information
@login_required
def update_user(request):
    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            user = u_form.save(commit=False)
            password = u_form.cleaned_data.get('password')
            if password:
                user.set_password(password)
            user.save()

            p_form = ProfileUpdateForm(request.POST, instance=profile)
            if p_form.is_valid():
                p_form.save()
                messages.success(request, 'Your profile was successfully updated!')
                if password:
                    updated_user = authenticate(username=user.username, password=password)
                    if updated_user is not None:
                        login(request, updated_user)
                        update_session_auth_hash(request, user)
                return redirect('core:profile')
            else:
                messages.error(request, 'There was an error updating your profile. Please correct the errors below.')
        else:
            messages.error(request, 'There was an error updating your profile. Please correct the errors below.')
    else:
        u_form = UserUpdateForm(instance=request.user)

    return render(request, 'core/update_user.html', {
        'u_form': u_form,
    })

# Home page
def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')[:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

# Category items page
def category_items(request, category_id):
    category_obj = get_object_or_404(Category, pk=category_id)
    items = Item.objects.filter(category_id=category_id, is_sold=False)
    return render(request, 'core/category_items.html', {
        'category': category_obj,
        'items': items,
    })

def faq_view(request):
    return render(request, 'core/faq.html')

# Contact page
def contact(request):
    return render(request, 'core/contact.html')

# Student portal page

def student_portal(request):
    return render(request, 'core/student_portal.html')

# Student practical page

def student_practical(request):
    return render(request, 'core/student_practical.html')

# About page
def about(request):
    return render(request, 'core/about.html')

# Gallery page
def gallery(request):
    return render(request, 'core/gallery.html')

# Ready to wear page
def ready_to_wear(request):
    return render(request, 'core/ready_to_wear.html')

# Ebook page
def ebook(request):
    return render(request, 'core/ebook.html')

# Training page
def training(request):
    return render(request, 'core/training.html')

# Custom made page
def custom_made(request):
    return render(request, 'core/custom_made.html')

# Courses page

def courses(request):
    return render(request, 'core/courses.html')

# Market place page
def market_place(request):
    return render(request, 'core/market_place.html')




# User login page
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.user
            try:
                profile = user.profile
                login(request, user)
                messages.info(request, f"You are now logged in as {user.username}.")
                return redirect('core:index')
            except ObjectDoesNotExist:
                messages.error(request, "User has no profile.")
                return redirect('core:signup')
    else:
        form = LoginForm()
    return render(request, 'core/login.html', {'form': form})





def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['terms_accepted']:
                user = form.save()
                # Assuming Profile and Profile.objects.filter(user=user) exist
                if not Profile.objects.filter(user=user).exists():
                    Profile.objects.create(user=user)

                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                if user:
                    login(request, user)
                    messages.success(request, 'You have successfully created an account and logged in!')
                    return redirect('core:index')
                else:
                    messages.error(request, 'Invalid username or password after signup.')
                    return redirect('core:signup')
            else:
                # Redirect to terms and conditions view if terms are not accepted
                return redirect('core:terms_and_conditions')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {'form': form})

def terms_and_conditions_view(request):
    return render(request, 'core/terms_and_conditions.html')










# User logout
@login_required
def user_logout(request):
    logout(request)
    messages.info(request, "You have been logged out.")
    return redirect('core:index')

# Delete account page
@login_required
def delete_account(request):
    if request.method == 'POST':
        form = AccountDeletionForm(request.POST)
        if form.is_valid():
            reason = form.cleaned_data['reason_for_deletion']
            send_account_deletion_email(request.user.email, reason)

            user = request.user
            logout(request)
            user.delete()

            messages.success(request, 'Your account has been deleted successfully.')
            return redirect('core:index')
    else:
        form = AccountDeletionForm()

    return render(request, 'core/account_delete.html', {'form': form})



# Send account deletion email
def send_account_deletion_email(email, reason):
    subject = 'Account Deletion Request'
    html_message = render_to_string('core/account_deletion_email.html', {'reason': reason})
    plain_message = strip_tags(html_message)

    try:
        send_mail(subject, plain_message, 'uwajohn101@gmail.com', [email], html_message=html_message)
        logger.info(f"Account deletion email sent to {email}")
    except Exception as e:
        logger.error(f"Failed to send account deletion email to {email}: {e}")








def cookies_view(request):
    return render(request, 'core/cookies.html')






class ForgotPasswordView(View):
    def get(self, request):
        # Clear the session if it exists
        if 'email' in request.session:
            del request.session['email']
        return render(request, 'core/forgot_password.html')

    def post(self, request):
        try:
            email = request.POST.get('email')
            user = User.objects.get(email=email)
            otp_profile, created = otp_Profile.objects.get_or_create(user=user)
            
            # Generate OTP and set its expiration time
            otp = random.randint(100000, 999999)
            otp_profile.otp = otp
            otp_profile.otp_created_at = timezone.now()
            otp_profile.save()
            
            # Send OTP via email
            send_mail(
                'Password Reset OTP',

core/templates/core/account_deletion_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account Deletion</title>
</head>
<body>
    <p>
        Dear user,
    </p>
    <p>
        Your account has been deleted from our platform. Below is the reason you provided:
    </p>
    <p>
        {{ reason }}
    </p>
    <p>
        If you did not request this action, please contact us immediately at support@prouessefashion.com.
    </p>
    <p>
        Best regards,
        <br>
        PROUESSE Fashion Support Team
    </p>
</body>
</html>

core/templates/core/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <!-- Boxicons CSS -->
  <link rel="stylesheet" href="/static/css/boxicons.min.css">
  <!-- Owl Carousel CSS -->
  <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/custom_admin.css' %}">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="/static/css/icons.css">
  <link rel="stylesheet" href="/static/css/style.css">

  <title>{% block title %}{% endblock %} | Prouesse</title>
  <link rel="icon" type="image/x-icon" href="{% static 'images/scissors.png' %}">
</head>
<body data-bs-spy="scroll" data-bs-target=".navbar">
  {% include 'core/navbar.html' %}

  {% if messages %}
    <ul>
      {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}


  <!-- Content Container Start -->
  <div class="container content-container">
    {% block content %}
    {% endblock %}
  </div>
  <!-- Content Container End -->

  <!-- Footer Start -->
  <div class="container-fluid bg footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
      <div class="row g-5">
        <div class="col-lg-3 col-md-6">
          <h1 class="m-0"><i class="fa fa-scissors me-3"></i>PROUESSE</h1>
          <p>We believe in fostering creativity, encouraging innovation, and preparing our students to become the future leaders of fashion.</p>
          <div class="col-auto">
            <div class="row gx-0">
              <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-whatsapp fw-normal"></i></a>
              <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-facebook-f fw-normal"></i></a>
              <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-pinterest fw-normal"></i></a>
              <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-instagram fw-normal"></i></a>
              <a class="btn btn-sm btn-outline-light btn-sm-square" href=""><i class="fab fa-youtube fw-normal"></i></a>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <h5 class="text-light mb-4">Contact</h5>
          <p><i class="fa fa-phone me-3"></i>+447466023608</p>
          <p><i class="fa fa-envelope me-3"></i>support@prouessefashion.com</p>
        </div>
        <div class="col-lg-3 col-md-6">
          <h5 class="text-light mb-4">Quick Links</h5>
          <a class="btn btn-link" href="{% url 'core:about' %}">About Us</a>
          <a class="btn btn-link" href="{% url 'core:contact' %}">Contact Us</a>
          <a class="btn btn-link" href="{% url 'core:faq' %}">FAQ</a>
          <a class="btn btn-link" href="{% url 'item:items' %}">Market Place</a>
          <a class="btn btn-link" href="{% url 'core:signup' %}">Sign Up</a>
          <a class="btn btn-link" href="{% url 'gallery:image_gallery' %}">Gallery</a>
          <a class="btn btn-link" href="{% url 'core:terms_and_conditions' %}">Cookies & Terms Policy</a>
        </div>
        <div class="col-lg-3 col-md-6">
          <h5 class="text-light mb-4">Newsletter</h5>
          <p>Subscribe to our Newsletter</p>
          <div class="position-relative mx-auto" style="max-width: 400px">
            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email"/>
            <button type="button" class="btn btn-brand position-absolute top-0 end-0 mt-2 me-2">Subscribe</button>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid copyright">
      <div class="container">
        <div class="row">
          <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
            &copy; <a href="#">PROUESSE</a>, All Right Reserved.
          </div>
          <div class="col-md-6 text-center text-md-end">
            Designed By <a href="https://cipherknights.biz">Cipher Knights</a>
            <br />Contact us at: <a href="mailto:support@cipherKnights.com" class="email-link">support@cipherKnights.com</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer End -->

<!-- Cookie section -->
<div id="cookie-consent-banner" class="bg-dark text-white p-3 fixed-bottom">
  <div class="container d-flex justify-content-between align-items-center">
      <p class="mb-0">We use cookies to ensure you get the best experience on our website. 
          <a href="{% url 'core:cookies' %}" id="read-more" class="text-warning">Read more</a>.
      </p>
      <div class="cookie-buttons">
          <button id="accept-cookies" onclick="acceptCookies()" class="btn btn-warning me-2">Accept</button>
          <button id="deny-cookies" onclick="denyCookies()" class="btn btn-secondary">Deny</button>
      </div>
  </div>
</div>


  <!-- Back to Top -->
  <a href="#" class="btn btn-primary btn-primary-outline-0 btn-md-square back-to-top"><i class="fa fa-arrow-up"></i></a>  

  <!-- JavaScript files -->
  <script src="/static/js/bootstrap.bundle.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/app.js"></script>
  <script src="/static/js/cookie.js"></script>
</body>
</html>

<style>
  #cookie-consent-banner {
    z-index: 1000; /* Make sure it's on top of other content */
}
</style>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}

     <!-- Contact Start -->
     <div class="container-fluid booking py-5 mt-4">
        <div class="container py-5">
            <div class="row g-5 align-items-center">

                
                <div class="col-lg-6">
                    <h2>Get in Touch</h2>
                    <p><i class="text-light fa fa-phone me-3"></i>+447466023608</p>
                    <p><i class="text-light fa fa-envelope me-3"></i>support@prouessefashion.com</p>
                    <p class="text-white mb-4"><span class="text-custom">100%</span> We are here for you any time you need our services.</p>
                    
                    <form method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control bg-white border-0" id="id_name" name="name" placeholder="Your Name">
                                    <label for="id_name">Your Name</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="email" class="form-control bg-white border-0" id="id_email" name="email" placeholder="Your Email">
                                    <label for="id_email">Your Email</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control bg-white border-0" id="id_phone" name="phone" placeholder="Your Phone Number">
                                    <label for="id_phone">Your Phone Number</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <select class="form-select bg-white border-0" id="id_service" name="service">
                                        <option value="" disabled selected>Select Service</option>
                                        <option value="Training">Training</option>
                                        <option value="Ready to Wear Dress">Ready to Wear Dress</option>
                                        <option value="Custom Made Dress">Custom Made Dress</option>
                                        <option value="Others">Others</option>
                                    </select>
                                    <label for="id_service">Service</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea class="form-control bg-white border-0" id="id_message" name="message" placeholder="Special Request" style="height: 100px"></textarea>
                                    <label for="id_message">Special Request</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary text-white w-100 py-3" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6">
                    <h5 class="section-booking-title pe-3">Meeting</h5>
                    <h1 class="text-white mb-4">Online Meeting</h1>
                    <p class="text-white mb-4">You can schedule a Zoom meeting with our admin for more clarification if necessary.</p>
                    <a href="https://calendly.com/estheradanma010/prouesse-fashion-meeting" id="scheduleMeetingButton" class="btn btn-light text-dark rounded-pill py-3 px-5 mt-2">Schedule a meeting</a>
                </div>
            </div>
        </div>
    </div>
    <!-- contact End -->
{% endblock %} 

<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">

 <!-- Calendly badge widget end -->
 <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>

 <script>
        //Calendly linking
document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('scheduleMeetingButton').addEventListener('click', function(event) {
        event.preventDefault(); // Prevent the default link behavior
        Calendly.initPopupWidget({
            url: 'https://calendly.com/estheradanma010/prouesse-fashion-meeting',
            color: '#0069ff',
            textColor: '#ffffff',
            branding: false
        });
    });
});
 </script>

core/templates/core/delete_account.html
{% extends 'base.html' %}

{% block content %}
  <h2>Delete Account</h2>
  <p>Please select a reason for deleting your account:</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Delete Account</button>
  </form>
{% endblock %}

core/templates/core/ebook.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Contact{% endblock %}

{% block content %}
<!-- Page Header Start -->
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Student Portal</h2>
            </div>
            <div class="col-12">
                <a href="{% url 'core:student_portal' %}">Student Portal</a>
                <a href="{% url 'gallery:gallery' %}">Video Gallery</a>
                <a href="{% url 'gallery:image_gallery' %}">Image Gallery</a>
                 <!--<a href="{% url 'gallery:upload_delete_videos' %}">Upload & Delete Videos</a>-->
                <a href="{% url 'core:ebook' %}">Ebooks</a>
            </div>
        </div>
    </div>
  </div>
  <!-- Page Header End -->


  
{% endblock %} 

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h1 class="mb-0 text-center">Login</h1>
                </div>
                <div class="card-body" style="background-color: #c0c0c0;">
                    <form method="post" action=".">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if form.errors or form.non_field_errors %}
                        <div class="alert alert-danger">
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div>{{ error }}</div>
                                {% endfor %}
                            {% endfor %}
                            {{ form.non_field_errors }}
                        </div>
                        {% endif %}
                        <button type="submit" class="btn btn-primary rounded-pill px-4">Submit</button>
                    </form>
                    <div class="mt-3">
                        <a href="{% url 'core:forgot_password' %}" style="color: #990f4b;">Forgot password?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3 text-center">
        Don't have an account? <a href="{% url 'core:signup' %}" style="color: #990f4b;">Sign Up</a>
    </div>
</div>
{% endblock %}